#pragma once

#include <credentialprovider.h>

enum BDFR_FIELD_ID : DWORD
{
    BFI_PROVIDER_NAME = 0,
    BFI_STATUS_TEXT = 1,
    BFI_INFO_LINK = 2,
    BFI_NUM_FIELDS
};

struct BDFR_FIELD_STATE_PAIR
{
    CREDENTIAL_PROVIDER_FIELD_STATE state;
    CREDENTIAL_PROVIDER_FIELD_INTERACTIVE_STATE interactive;
};

inline wchar_t BDFR_PROVIDER_NAME_LABEL[] = L"BDFR LogonUI";
inline wchar_t BDFR_STATUS_LABEL[] = L"Status";
inline wchar_t BDFR_INFO_LABEL[] = L"About this preview";

inline const CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR BDFR_FIELDS[BFI_NUM_FIELDS] =
{
    { BFI_PROVIDER_NAME, CPFT_LARGE_TEXT, BDFR_PROVIDER_NAME_LABEL },
    { BFI_STATUS_TEXT,   CPFT_SMALL_TEXT, BDFR_STATUS_LABEL },
    { BFI_INFO_LINK,     CPFT_COMMAND_LINK, BDFR_INFO_LABEL }
};

inline constexpr BDFR_FIELD_STATE_PAIR BDFR_FIELD_STATES[BFI_NUM_FIELDS] =
{
    { CPFS_DISPLAY_IN_BOTH,          CPFIS_NONE },
    { CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE },
    { CPFS_DISPLAY_IN_SELECTED_TILE, CPFIS_NONE }
};
